In [1]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree

In [2]:
dataset = pd.read_csv(r'C:\Users\Dell\Downloads\Decision_Tree_ Dataset.csv')
dataset.head()

1      2    3     4    sum Unnamed: 5
0  201  10018  250  3046  13515        yes
1  205  10016  395  3044  13660        yes
2  257  10129  109  3251  13746        yes
3  246  10064  324  3137  13771        yes
4  117  10115  496  3094  13822        yes

In [3]:
dataset.columns = ['Initial payment', 'Last payment', 'Credit Score', 'House Number', 'Sum of amount', 'Result']
dataset

Initial payment  Last payment  Credit Score  House Number  Sum of amount  \
0                201         10018           250          3046          13515   
1                205         10016           395          3044          13660   
2                257         10129           109          3251          13746   
3                246         10064           324          3137          13771   
4                117         10115           496          3094          13822   
..               ...           ...           ...           ...            ...   
995              413         14914           523          4683          20533   
996              359         14423           927          4838          20547   
997              316         14872           613          4760          20561   
998              305         14926           897          4572          20700   
999              168         14798           834          4937          20737   

    Result  
0      yes  
1      yes  
2      yes  
3      yes  
4      yes  
..     ...  
995     No  
996     No  
997     No  
998     No  
999     No  

[1000 rows x 6 columns]

In [4]:
dataset['Result'] = pd.Categorical(dataset['Result'])
dataset.dtypes

Initial payment       int64
Last payment          int64
Credit Score          int64
House Number          int64
Sum of amount         int64
Result             category
dtype: object

In [5]:
dataset = pd.get_dummies(dataset, drop_first=True)  # To avoid dummy trap
dataset.head()

Initial payment  Last payment  Credit Score  House Number  Sum of amount  \
0              201         10018           250          3046          13515   
1              205         10016           395          3044          13660   
2              257         10129           109          3251          13746   
3              246         10064           324          3137          13771   
4              117         10115           496          3094          13822   

   Result_yes  
0           1  
1           1  
2           1  
3           1  
4           1

In [6]:
X = dataset.iloc[:,:-1]
X

Initial payment  Last payment  Credit Score  House Number  Sum of amount
0                201         10018           250          3046          13515
1                205         10016           395          3044          13660
2                257         10129           109          3251          13746
3                246         10064           324          3137          13771
4                117         10115           496          3094          13822
..               ...           ...           ...           ...            ...
995              413         14914           523          4683          20533
996              359         14423           927          4838          20547
997              316         14872           613          4760          20561
998              305         14926           897          4572          20700
999              168         14798           834          4937          20737

[1000 rows x 5 columns]

In [7]:
y = dataset.iloc[:, -1:]
y

Result_yes
0             1
1             1
2             1
3             1
4             1
..          ...
995           0
996           0
997           0
998           0
999           0

[1000 rows x 1 columns]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 20) 

#function to perform training with entropy
clf_entropy= DecisionTreeClassifier(criterion = 'entropy', random_state=100, max_depth=3, min_samples_leaf=5)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [9]:
y_pred_en = clf_entropy.predict(X_test)
y_pred_en

array([0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1], d

In [10]:
print('Accuracy =', accuracy_score(y_test, y_pred_en)*100)

Accuracy = 100.0


In [11]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred_en)

array([[156,   0],
       [  0, 144]], dtype=int64)

In [12]:
X_in = np.array([500,12000,501,4525,18000])         # take an example
X_in.reshape(-1,1)

array([[  500],
       [12000],
       [  501],
       [ 4525],
       [18000]])

In [13]:
y_pred_en = clf_entropy.predict([X_in])       
y_pred_en

array([0], dtype=uint8)

In [14]:
 # answer of the example is that he will not pay the loan

In [15]:
X_in = np.array([300,9000,251,4525,12000])         # take an example
X_in.reshape(-1,1)

array([[  300],
       [ 9000],
       [  251],
       [ 4525],
       [12000]])

In [16]:
y_pred_en = clf_entropy.predict([X_in])       
y_pred_en

array([1], dtype=uint8)

In [17]:
# he will pay the loan

In [18]:
from sklearn.externals.six import StringIO
from IPython.display import Image
from sklearn. tree import export_graphviz
import pydotplus
import graphviz

In [19]:
dot_data = StringIO()
export_graphviz(clf_entropy, out_file = dot_data, filled = True, rounded = True, special_characters = True)

In [20]:
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png('Tree_Loan.png')

True